# Generated by Django 4.0 on 2022-01-11 02:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteiner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='invalid', message='Permitido somente um código no formato TEST1234567', regex=re.compile('[a-zA-Z]{4}[0-9]{7}'))], verbose_name='Número')),
                ('categoria', models.CharField(choices=[('IMPORTACAO', 'Importação'), ('EXPORTACAO', 'Exportação')], max_length=10)),
                ('status', models.CharField(choices=[('CHEIO', 'Cheio'), ('VAZIO', 'Vazio')], max_length=5)),
                ('tipo', models.CharField(choices=[('20', '20'), ('40', '40')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conteineres', to='cliente.cliente')),
            ],
            options={
                'verbose_name': 'Contêiner',
                'verbose_name_plural': 'Contêineres',
            },
        ),
    ]
